ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubuntu/rebase"
ARG BASE_VERSION="noble"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubuntu"

USER gbraad

ENTRYPOINT ["/bin/zsh"]
