ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/ubuntu"
ARG BASE_VERSION="noble"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubuntu"

USER root

RUN apt-get update \
    && apt-get install -y \
        openssh-client \
        openssh-server \
    && rm -rf /var/lib/apt/lists/*

COPY assets/tailscaled /etc/init.d/tailscaled

RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt update \
    && sudo apt install -y \
        gh \
    && rm -rf /var/lib/apt/lists/*
