name: build containers
run-name: building containers

on:
  workflow_dispatch:

jobs:
  build:
    name: build-containers
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - rebase
        run: |
          podman build -t ghcr.io/gbraad-devenv/ubuntu/rebase:noble \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-dotfiles/ubuntu" \
            --build-arg=BASE_VERSION="noble" \
            -f containers/Containerfile-rebase .
      - name: Run podman build - dotfiles
        run: |
          podman build -t ghcr.io/gbraad-devenv/ubuntu/dotfiles:noble \
            --build-arg=BASE_IMAGE="ghcr.io/gbraad-devenv/ubuntu/rebase" \
            -f containers/Containerfile-dotfiles .
      - name: Run podman build - systemd
        run: |
          podman build -t ghcr.io/gbraad-devenv/ubuntu/systemd:noble \
            -f containers/Containerfile-systemd .

      - name: Login to ghcr.io
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to ghcr.io - rebase
        run: |
          podman push ghcr.io/gbraad-devenv/ubuntu/rebase:noble
      - name: Push image to ghcr.io - dotfiles
        run: |
          podman push ghcr.io/gbraad-devenv/ubuntu/dotfiles:noble
      - name: Push image to ghcr.io - systemd
        run: |
          podman push ghcr.io/gbraad-devenv/ubuntu/systemd:noble
